# Generated by Django 4.2.6 on 2023-10-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pupil',
            new_name='Child',
        ),
    ]
