# Generated by Django 4.2.6 on 2023-10-26 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0004_rename_grades_grade_rename_skills_child_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='description_app.child'),
        ),
        migrations.AlterField(
            model_name='description',
            name='child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='description_app.child'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='czytanie',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='liczenie',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='pisanie',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1),
        ),
    ]
