# Generated by Django 4.2.6 on 2023-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0006_skill_alter_child_gender_delete_grade_skill_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='child',
        ),
        migrations.AddField(
            model_name='skill',
            name='child',
            field=models.ManyToManyField(null=True, to='description_app.child'),
        ),
    ]
