# Generated by Django 4.2.6 on 2023-10-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0007_alter_child_options_remove_skill_child_skill_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='child',
        ),
        migrations.AddField(
            model_name='skill',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='description_app.child'),
        ),
    ]
