# Generated by Django 4.2.6 on 2023-10-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0008_remove_skill_child_skill_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='child',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='grade',
        ),
        migrations.CreateModel(
            name='ChildSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1)),
                ('child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='description_app.child')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='description_app.skill')),
            ],
        ),
    ]
