# Generated by Django 4.2.6 on 2023-10-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0009_remove_skill_child_remove_skill_grade_childskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childskill',
            name='grade',
        ),
        migrations.AddField(
            model_name='skill',
            name='child',
            field=models.ManyToManyField(through='description_app.ChildSkill', to='description_app.child'),
        ),
        migrations.AddField(
            model_name='skill',
            name='grade',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1, null=True),
        ),
    ]
