# Generated by Django 4.2.6 on 2023-10-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0010_remove_childskill_grade_skill_child_skill_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='child',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='grade',
        ),
        migrations.AddField(
            model_name='childskill',
            name='grade',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='childskill',
            name='child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='description_app.child'),
        ),
    ]
