# Generated by Django 4.2.6 on 2023-10-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0011_remove_skill_child_remove_skill_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childskill',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='description_app.child'),
        ),
    ]
