# Generated by Django 4.2.6 on 2023-10-26 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0012_alter_childskill_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childskill',
            name='grade',
        ),
    ]
