# Generated by Django 4.2.6 on 2023-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0014_childskill_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childskill',
            name='child',
        ),
        migrations.AddField(
            model_name='childskill',
            name='child',
            field=models.ManyToManyField(null=True, to='description_app.child'),
        ),
    ]
