# Generated by Django 4.2.6 on 2023-10-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0015_remove_childskill_child_childskill_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='skill',
            field=models.ManyToManyField(through='description_app.ChildSkill', to='description_app.skill'),
        ),
        migrations.RemoveField(
            model_name='childskill',
            name='child',
        ),
        migrations.AddField(
            model_name='childskill',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='description_app.child'),
        ),
    ]
