# Generated by Django 4.2.6 on 2023-10-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0016_child_skill_remove_childskill_child_childskill_child'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='childskill',
            unique_together={('child', 'skill')},
        ),
    ]
