# Generated by Django 4.2.6 on 2023-10-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0017_alter_childskill_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
