# Generated by Django 4.2.6 on 2023-10-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0018_skill_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='response_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
