# Generated by Django 4.2.3 on 2023-10-27 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0019_skill_response_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='response_text',
        ),
        migrations.CreateModel(
            name='ResponseText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(max_length=200, null=True)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='description_app.skill')),
            ],
        ),
    ]
