# Generated by Django 4.2.6 on 2023-10-27 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0020_remove_skill_response_text_responsetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetext',
            name='grade',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
