# Generated by Django 4.2.6 on 2023-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0024_alter_responsetext_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
