# Generated by Django 4.2.6 on 2023-11-06 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0025_child_description_delete_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childskill',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='description_app.child'),
        ),
        migrations.AlterField(
            model_name='responsetext',
            name='grade',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2)], max_length=2, null=True),
        ),
    ]
