# Generated by Django 4.2.6 on 2023-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0026_alter_childskill_child_alter_responsetext_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetext',
            name='grade',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
