# Generated by Django 4.2.6 on 2023-11-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0029_alter_childskill_grade_alter_responsetext_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childskill',
            name='grade',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='responsetext',
            name='grade',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], max_length=1, null=True),
        ),
    ]
