# Generated by Django 4.2.6 on 2023-11-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0030_alter_childskill_grade_alter_responsetext_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='short_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
