# Generated by Django 4.2.6 on 2023-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description_app', '0031_child_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='short_name',
            field=models.CharField(max_length=30),
        ),
    ]
